apiVersion: v2
name: template-store
description: A Helm chart for the Template Store & Blog Platform application.
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: postgresql
  version: "12.x.x"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled
